### ISSUE TITLE
custom elements should default to display:block

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-element#31]
This gives a 0 x 0 svg:

```
<body>
  <div>
    <d3fc-svg  style="background: red; width: 400px; height: 200px"></d3fc-svg>
  </div>
</body>
```

... due to d3fc-svg being an inline element.

**Comment by chrisprice** [comment]
Whilst `canvas` and `svg` are `inline`, I don't think `inline` is an appropriate value here as we're using the elements size to derive the drawing surface dimensions, rather than the drawing surface having any form of intrinsic dimensions. 

I think both `block` and `inline-block` are appropriate in this situation. I'm leaning towards `block` in order to avoid unexpected baseline and vertical whitespace issues.
